### ISSUE TITLE
New tag for a release

### ISSUE THREAD

**Issue by jmcarcell** [key4hep/k4GeneratorsConfig#24]
Can this repository be tagged, so that a certain version can be built in the next release?

**Comment by jmcarcell** [comment]
@dirkzerwas which commit or this repository should I build for the next stable release (in `/cvmfs/sw.hsf.org/`)? We should have a tag for reproducibility, even if it doesn't have any specific meaning.

**Comment by dirkzerwas** [comment]
@jmcarcell I tagged v0.1 "Gamma Release" to have a simple reference

**Comment by jmcarcell** [comment]
Great, many thanks!
